### ISSUE TITLE
time.Add() crashes

### ISSUE THREAD

**Issue by glycerine** [gijit/gi#46]
~~~
nearest-git-tag: 'v1.9.3'
git-branch: 'master'
go-version: 'go_version_go1.10_darwin/amd64'
luajit-version: 'LuaJIT_2.1.0-beta3+jea-int64-additions'
==================
Using static prelude.
gi> import "time"
import "time"

elapsed: '190.871µs'
gi> b := time.Now().Add(time.Second)
b := time.Now().Add(time.Second)
problem in golua_callgofunction, panic happened: '[string "..."]:7: cannot convert Go function argument #0: cannot convert proxy (time.Time) to time.Duration' at
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xc4202f72d0, 0x4a9f800, 0xc4201a3680)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.golua_callgofunction.func1()
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/golua.go:149 +0x6e
panic(0x4a9f800, 0xc4201a3680)
	/usr/local/go/src/runtime/panic.go:505 +0x229
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).RaiseError(0xc42008ab80, 0xc4200466c0, 0x59)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lua.go:760 +0x1fc
github.com/gijit/gi/vendor/github.com/glycerine/luar.goToLuaFunction.func1(0xc42008ab80, 0x47)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/luar/luar.go:321 +0x3f5
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.golua_callgofunction(0x61ec688, 0x0, 0x1, 0x56d0378, 0x50, 0x0)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/golua.go:191 +0x5af
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua._cgoexpwrap_ffe5ce162ef2_golua_callgofunction(0x61ec688, 0x0, 0x1, 0x56d0378, 0x50, 0x493ef94)
	_cgo_gotypes.go:1703 +0x53
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua._Cfunc_lua_pcall(0x56d0378, 0x1, 0x1, 0x0)
	_cgo_gotypes.go:1204 +0x4d
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).pcall.func1(0x56d0378, 0x1, 0x1, 0xc4204ec260)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lua.go:179 +0x6e
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).pcall(0xc4201aedc0, 0x1, 0x0, 0x1, 0x2)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lua.go:179 +0x49
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).callEx(0xc4201aedc0, 0x1, 0x0, 0x5700001, 0x0, 0x0)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lua.go:203 +0x18c
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).Call(0xc4201aedc0, 0x1, 0x0, 0x0, 0x1)
	/Users/jaten/go/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lua.go:220 +0x44
github.com/gijit/gi/pkg/compiler.(*Goro).privateRun(0xc42020dd50, 0xc4202c5b80, 0x29c, 0x2c0, 0x4059a01, 0x0, 0x0)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/goro.go:301 +0x475
github.com/gijit/gi/pkg/compiler.(*Goro).handleTicket(0xc42020dd50, 0xc4204fc580)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/goro.go:217 +0x54e
github.com/gijit/gi/pkg/compiler.(*Goro).do(0xc42020dd50, 0xc4204fc580)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/goro.go:253 +0x35
github.com/gijit/gi/pkg/compiler.(*ticket).Do(0xc4204fc580, 0xc4202c58c0, 0x29c)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/goro.go:259 +0x10e
github.com/gijit/gi/pkg/compiler.LuaRun(0xc4201c1840, 0xc4202c58c0, 0x29c, 0x1, 0xc4202f7da8, 0x1)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/luaUtil.go:535 +0x5a
github.com/gijit/gi/pkg/compiler.(*Repl).Eval(0xc42023b560, 0xc420038220, 0x20, 0x0, 0x0)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/repl_luajit.go:549 +0x46f
github.com/gijit/gi/pkg/compiler.(*Repl).Loop(0xc42023b560)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/repl_luajit.go:187 +0x67
github.com/gijit/gi/pkg/compiler.(*GIConfig).LuajitMain(0xc4201c1820)
	/Users/jaten/go/src/github.com/gijit/gi/pkg/compiler/repl_luajit.go:93 +0x64
main.main()
	/Users/jaten/go/src/github.com/gijit/gi/cmd/gi/repl.go:59 +0x21a


elapsed: '90.681766ms'
gi> 
~~~

**Comment by glycerine** [comment]
fixed in v1.9.6
