### ISSUE TITLE
SEGSV/overflow when embedding while importing stdlib "plugin"

### ISSUE THREAD

**Issue by gstvg** [gijit/gi#55]
Hi. First of all, thanks for this great package!

This code runs fine:

```
package main

import (
	"github.com/gijit/gi/cmd/gi/prelude"
)

func main() {
	compiler.NewLuaVmWithPrelude(compiler.NewGIConfig())
}
```

While this:
```

package main

import (
	"github.com/gijit/gi/cmd/gi/prelude"
	"plugin"
)

func main() {
	compiler.NewLuaVmWithPrelude(compiler.NewGIConfig())
	_=plugin.Plugin{}
}
```

Output that:

```
/tmp/___go_build_bug_go: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
/tmp/___go_build_bug_go: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2e7ff710 pc=0x101c677]

runtime stack:
runtime.throw(0x127aa28, 0x2a)
	/usr/local/go/src/runtime/panic.go:619 +0x81
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:372 +0x28e

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xffdb30, 0xc4201b1ad8, 0x8)
	/usr/local/go/src/runtime/cgocall.go:128 +0x64 fp=0xc4201b1aa8 sp=0xc4201b1a70 pc=0x7594e4
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua._Cfunc_luaL_openlibs(0x7f0b2f263378)
	_cgo_gotypes.go:744 +0x41 fp=0xc4201b1ad8 sp=0xc4201b1aa8 pc=0xd8b721
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).OpenLibs.func1(0x7f0b2f263378)
	/home/gustavo/work/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lauxlib.go:191 +0x56 fp=0xc4201b1b10 sp=0xc4201b1ad8 pc=0xd98a36
github.com/gijit/gi/vendor/github.com/glycerine/golua/lua.(*State).OpenLibs(0xc420082c00)
	/home/gustavo/work/src/github.com/gijit/gi/vendor/github.com/glycerine/golua/lua/lauxlib.go:191 +0x2e fp=0xc4201b1b28 sp=0xc4201b1b10 pc=0xd9229e
github.com/gijit/gi/vendor/github.com/glycerine/luar.Init(0x11ba4c0)
	/home/gustavo/work/src/github.com/gijit/gi/vendor/github.com/glycerine/luar/luar.go:158 +0x45 fp=0xc4201b1cb8 sp=0xc4201b1b28 pc=0xd9fbb5
github.com/gijit/gi/cmd/gi/prelude.NewLuaVmWithPrelude(0xc42000d8a0, 0xc42000d8c0, 0xc4201b1f78, 0xc42009e058)
	/home/gustavo/work/src/github.com/gijit/gi/cmd/gi/prelude/luaUtil.go:93 +0x17e fp=0xc4201b1f58 sp=0xc4201b1cb8 pc=0xf5390e
main.main()
	/home/gustavo/work/src/xxxx/bug.go:9 +0x45 fp=0xc4201b1f88 sp=0xc4201b1f58 pc=0xffd0a5
runtime.main()
	/usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc4201b1fe0 sp=0xc4201b1f88 pc=0x787a82
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4201b1fe8 sp=0xc4201b1fe0 pc=0x7b5d91

goroutine 4 [syscall]:
os/signal.signal_recv(0xc420052fc8)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

Process finished with exit code 2
```

I'm running Ubuntu 16.04 64bits with Go 1.10

**Comment by gstvg** [comment]
Go env:
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/gustavo/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/gustavo/work"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build252185218=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by glycerine** [comment]
Sadly plugin isn't a very well supported package in Golang land.

In fact, I wrote gi and used LuaJIT is response to that situation. 

So if you want to use plugins, this will be going very off road. LuaJIT itself
of course can load any .so dynamically at runtime.

But let's get back to the start. What are you actually trying to do? Maybe there is a better way.

**Comment by gstvg** [comment]
I'm trying to allow dynamic scripting on an app, including Go scripting. At first, i would use this library only, but then started playing with plugin lib. As plugin wont work on windows, i would just use this on windows, and plugin on the rest. But then i wanted to support an edge case where someone developing locally on linux and deploying on windows, thus requiring both plugin and this lib on the linux binary. But now i think i may end up using this lib only, or one lib per platform. But after all, i filled this issue imagining this bug could be something inside this lib that could be triggered on other cases. But with your response, i imagine it is related to plugin and cgo libs. You think it worth opening an issue on Go repo? Thanks!

**Comment by glycerine** [comment]
@gstvg for dynamic scripting in Go you should also try https://github.com/cosmos72/gomacro. Gomacro is a little more mature, and can be faster -- I've gone over to using it myself in fact. The docs say the gomacro works on windows.

**Comment by gstvg** [comment]
Wow, thanks, I don't know how i missed this package on my search. Thanks again!
